# Streamlit configuration file

[theme]
# General theme settings
base = "light"  # Set the base theme to light, can be 'dark' as well
primaryColor = "#d97857"  # Coral color for primary actions
backgroundColor = "#f1efe7"  # Light background for the app
secondaryBackgroundColor = "#f6f4ef"  # Subtle light background for secondary elements
textColor = "#333333"  # Dark text for readability
font = "sans serif"  # Default font

